# The Diamond DataMine: Using Data to Find the Perfect Diamond {#piece-of-mine}

#### Keywords

diamonds, data, value, engagement ring, machine learning, website scraping

## Mo' money, mo' problems

An engagement ring is one of the most important and expensive purchases a person will make (the average ring bought in the US costs almost $5,000)^[https://www.weddingwire.com/press-center/press-releases/2016/weddingwire-announces-2015-newlywed-report.html]. Engagement rings are a big business, with annual sales of $5 billion accounting for almost 20% of the diamond jewelery market ^[http://www.idexonline.com/FullArticle?Id=38054]. As anyone who has been through the process of purchasing one can attest, the experience can be stressful. Most buyers are inexperienced with the world of diamonds and jewelry. They want the purchase to be perfect as it is intended for their life partner and will last the remainder of their lifetimes. Balancing cost with quality can be very tricky for the inexperienced. Users must navigate different retailers' sites and compare inconsistent displays of relevant data. The lack of transparent data can lead to costly mistakes and buyer's remorse. That's where The Diamond DataMine comes in. 

## Mining Data

The Diamond DataMine site asks users for the basic characteristics they are searching for (cut of diamond, carat, clarity, etc.) as well as a budget. It then returns diamonds that meet those criteria listed with a quality to cost ratio so that users can purchase the diamond with the best value within their price range. The site accomplishes this by scraping data from the major online retailers of diamonds (e.g. Blue Nile, Brilliant Earth). If scraping is prohibited by a retailer's terms of use, data may be aquired through licensing deals. The Diamond DataMine model will have been taught how to value diamonds by having data on thousands of diamond appraisals fed to it before the product is launched. Data fed into the model will include but not be limited to: cut, carat, clarity, color, cost, appraisal value, physical dimensions, grading reports, ASET images, and videos of the diamond. Based on factors such as these, the platform will be able to determine the typical selling price of a diamond based on its characteristics and report to the user a composite value score relative to its price. The model will continue to collect data as time passes and will weigh recent data more heavily than older data to accurately capture current market conditions.

## A Diamond in the Rough

The Diamond DataMine's will simplify the diamond hunter’s search by providing a simple and easy to understand one-stop-shop solution. Limitations of the platform include inconsistent data provided by different retailers. Some provide detailed image and video data while others do not. This could cause inaccuracies in the model. Additionally, while the model will evaluate the value of the diamond relative to price, it does not take into account other factors of the diamond purchasing process such as the reputation, customer service, or return policy of the online vendor. A user will need to take these factors into account before making a final purchasing decision. However, these factors pale in comparison to the base cost of the diamond itself and the stress of navigating multiple sites, not knowing what to look for and whether or not a certain price is a good deal. The Diamond DataMine will give buyers peace of mind.  

