# Discover what’s for dinner {#RecipeMate}

#### Keywords

easy cooking, kitchen management, recipe suggestions, machine learning

## You open the fridge and...

You come home from a long day at work and open the fridge. “What am I going to make for dinner tonight?” Figuring out what you can make with the assortment of ingredients in your kitchen is a cognitive load you just don’t need in your busy day. That’s where RecipeMate steps in to help the everyday consumer. The product tracks what you have in your fridge and suggests possible recipes that you can make. 

## Dinner made easy!

RecipeMate works by monitoring the contents of its user’s fridge, pantry, and freezer via small cameras the user installs in those locations. It then feeds the images it captures to a machine learning algorithm. The algorithm has been trained on a vast corpus of images of groceries so it can identify the contents of the user's kitchen. Additionally, it is able to estimate quantities based on the images it captures. The results are stored in a database users are able to access via the web or mobile or tablet application. Users can interact with the database to verify the algorithm's matches and correct mischaracterized items. The algorithm will incorporate this user feedback to strengthen its visual matching capabilities.

The contents of the user's kitchen are then cross-referenced against a database of stored recipes that have been scraped from recipe websites such as allrecipes.com and foodnetwork.com. Results that match are returned to the user who will have the ability to filter the results based on cuisine, length of preparation time, user rating, and specific ingredients. During profile creation, the user can let RecipeMate know what type of cookware he or she possesses as well as a relative cooking skill level, so the app can calibrate the recipes it presents to the user’s capabilities. The initial recipes and recipe rating data RecipeMate will use will come from the recipe sites it scrapes. However, over time, RecipeMate will collect its own recipes and recipe ratings from its users and seek to build its own independent data.

As the product becomes more mature and has a larger body of user data to pull from, the product's offerings could be expanded in several different directions. To better meet user needs, an additional layer of machine learning could be implemented to display recipe results that are most likely to meet the user’s preferences based on historical choices. Capabilities to monitor expiration dates could be added so that the app prioritizes recipes that use ingredients that will expire shortly. The app could also alert the user when food expires and needs to be tossed. Finally, the app could be adapted to help the user with their grocery shopping experience. For example, the user could browse through the app's archive of recipes and select one he or she would like to make. The app would then tell the user which ingredients the user does not have and add them to a shopping list.

## Guess who's coming to dinner

With RecipeMate as a part of the household, the days of scrambling to figure out what’s in the fridge and what to make for dinner are over. In today's world, people spend almost four hours every week deciding what to eat ^[http://www.swnsdigital.com/2017/06/brits-spend-a-year-and-a-half-of-their-lives-deciding-what-to-eat/]. With RecipeMate, people can spend that time doing what they love!
